### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by shaeussler** [damienbod/AzureIoTHubDps#1]
If I run the CertsCreateChained console app the call to cc.NewIntermediateChainedCertificate on line 28 creates a System.NullReferenceException: 'Object reference not set to an instance of an object.'.

Version: 1.0.3

**Comment by damienbod** [comment]
Hi @shaeussler 

I don't have this problem, just tried running and it works.

Could you give me more info? Or try a dotnet restore, dotnet run?

Greetings Damien

**Comment by shaeussler** [comment]
Hi @damienbod 

dotnet --version: 3.1.102
OS: Windows 10, 1909
In the CertsCreateChained directory I run
dotnet  restore 
dotnet run
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at CertificateManager.CreateCertificates.ChainedConfiguration(BasicConstraints basicConstraints, ValidityPeriod validityPeriod, SubjectAlternativeName subjectAlternativeName, X509Certificate2 signingCertificate, OidCollection enhancedKeyUsages, X509KeyUsageFlags x509KeyUsageFlags, CertificateRequest request)
   at CertificateManager.CreateCertificates.NewECDsaChainedCertificate(DistinguishedName distinguishedName, BasicConstraints basicConstraints, ValidityPeriod validityPeriod, SubjectAlternativeName subjectAlternativeName, X509Certificate2 signingCertificate, OidCollection enhancedKeyUsages, X509KeyUsageFlags x509KeyUsageFlags, ECDsaConfiguration eCDsaConfiguration)
   at CertificateManager.CreateCertificatesClientServerAuth.NewIntermediateChainedCertificate(DistinguishedName distinguishedName, ValidityPeriod validityPeriod, Int32 pathLengthConstraint, String dnsName, X509Certificate2 parentCertificateAuthority)
   at CertsCreateChained.Program.Main(String[] args) in D:\Code\git\AzureIoTHubDps\CertsCreateChained\Program.cs:line 28

I added the CertificateManager project reference:

dotnet run
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at CertificateManager.CreateCertificates.ChainedConfiguration(BasicConstraints basicConstraints, ValidityPeriod validityPeriod, SubjectAlternativeName subjectAlternativeName, X509Certificate2 signingCertificate, OidCollection enhancedKeyUsages, X509KeyUsageFlags x509KeyUsageFlags, CertificateRequest request) in D:\Code\git\AspNetCoreCertificates\src\CertificateManager\CreateCertificates.cs:line 180
   at CertificateManager.CreateCertificates.NewECDsaChainedCertificate(DistinguishedName distinguishedName, BasicConstraints basicConstraints, ValidityPeriod validityPeriod, SubjectAlternativeName subjectAlternativeName, X509Certificate2 signingCertificate, OidCollection enhancedKeyUsages, X509KeyUsageFlags x509KeyUsageFlags, ECDsaConfiguration eCDsaConfiguration) in D:\Code\git\AspNetCoreCertificates\src\CertificateManager\CreateCertificates.cs:line 159
   at CertificateManager.CreateCertificatesClientServerAuth.NewIntermediateChainedCertificate(DistinguishedName distinguishedName, ValidityPeriod validityPeriod, Int32 pathLengthConstraint, String dnsName, X509Certificate2 parentCertificateAuthority) in D:\Code\git\AspNetCoreCertificates\src\CertificateManager\CreateCertificatesClientServerAuth.cs:line 106
   at CertsCreateChained.Program.Main(String[] args) in D:\Code\git\AzureIoTHubDps\CertsCreateChained\Program.cs:line 28

The following line creates the exception:
var issuerSubjectKey = signingCertificate.Extensions["Subject Key Identifier"].RawData;
The Extensions collection contains no "Subject Key Identifier".

Greetings

**Comment by shaeussler** [comment]
Hi @damienbod

It is a localization problem. 
See Issue https://github.com/rwatjen/AzureIoTDPSCertificates/issues/2
I added the solution from this issue and write the "item.Oid.FriendlyName" to the console:
            byte[] issuerSubjectKey = null;

            foreach (var item in signingCertificate.Extensions)
            {
               if (item.Oid.Value == "2.5.29.14")
               {
                  issuerSubjectKey = item.RawData;
                  Console.WriteLine(item.Oid.FriendlyName);
                  break;
               }
            }

Schlüsselkennung des Antragstellers

Greetings

**Comment by damienbod** [comment]
@shaeussler Thanks! 

Will fix this

**Comment by damienbod** [comment]
@shaeussler 

Should be fixed now, thanks for debugging this.

Greetings Damien
